In [1]:
#Specifically, feature hashing maps each category in a categorical feature to an integer within a pre-determined range
#Hash functions also come with a not-so-nice side effect i.e. they can hash different keys to the same integer value (we call it ‘collision’). It will certainly happen in this case as we had represented 1000 distinct categories as 10 columns.

#steps
#1-we need to fix is the length of the vector, or the number of dimensions, we are going to use
#2-Once we fix the number of dimensions we need a hash function
#that will take a string and return a number between 0 and n-1, in our case between 0 and 4. We can use any good hash function and you just used h(string) mod n to make it return a number between 0 and n-1.


#h(everything) mod 5 = 0
#h(is) mod 5 = 1
#h(well) mod 5 = 1
#h(planned) mod 5 = 3
#Once we have this we can simply construct our vector as: (0,1,1,3)

In [5]:
!pip install category_encoders

from category_encoders.hashing import HashingEncoder
import pandas as pd

Requirement already satisfied: category_encoders in /usr/local/lib/python3.10/dist-packages (2.6.1)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.22.4)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.10.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.13.5)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2022.7.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.1.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (23.1)

In [6]:
bunch = pd.read_csv('Boston.csv',)

In [7]:
bunch.sample(5)

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
198,199,0.03768,80.0,1.52,0,0.404,7.274,38.3,7.3090,2,329,12.6,392.20,6.62,34.6
41,42,0.12744,0.0,6.91,0,0.448,6.770,2.9,5.7209,3,233,17.9,385.41,4.84,26.6
426,427,12.24720,0.0,18.10,0,0.584,5.837,59.7,1.9976,24,666,20.2,24.65,15.69,10.2
145,146,2.37934,0.0,19.58,0,0.871,6.130,100.0,1.4191,5,403,14.7,172.91,27.80,13.8
172,173,0.13914,0.0,4.05,0,0.510,5.572,88.5,2.5961,5,296,16.6,396.90,14.69,23.1

In [8]:
X = pd.DataFrame(bunch.data, columns=bunch.feature_names)
y = bunch.target

AttributeError: ignored

In [ ]:
#not completed read this-  https://datasciencestunt.com/dealing-with-categorical-features-with-high-cardinality-feature-hashing/#google_vignette